version: '2'
services:
  wordpress:
    depends_on:
      - db
    build: Dockerfiles/wordpress
    image: conduction/openwebconcept:4.8
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-config.php:/var/www/html/wp-config.php
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  db:
#    build: Dockerfiles/mysql
    image: mysql:5.7
    volumes:
       - db_data:/var/lib/mysql:rw
    command: ["--ignore-db-dir=lost+found", "--innodb_use_native_aio=0"]
    environment:
      MYSQL_ROOT_PASSWORD: wp_project
      MYSQL_DATABASE: wp_project
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: wp_project
    networks:
      - back
networks:
  back:
volumes:
  db_data: {}