apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: {{ .Values.settings.name }}-{{ .Values.settings.env }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}-ingress
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
    {{- if and (eq $.Values.settings.env "prod") $.Values.settings.subpath }}

    - host: {{ $.Values.settings.domain }}
      http:
          paths:
                - path: /{{ $.Values.settings.subpath }}/(.*)
                  backend:
                    serviceName: {{ $.Values.settings.name }}
                    servicePort: 80
                - path: /{{ $.Values.settings.subpath }}(.*)
                  backend:
                    serviceName: {{ $.Values.settings.name }}
                    servicePort: 80
    {{- else if eq $.Values.settings.env "prod" }}

    - host: {{ $.Values.settings.domain }}
      http:
          paths:
            - path: /(.*)
            - backend:
                serviceName: {{ $.Values.settings.name }}
                servicePort: 80
    - host: www.{{ $.Values.settings.domain }}
      http:
          paths:
            - path: /(.*)
            - backend:
                serviceName: {{ $.Values.settings.name }}
                servicePort: 80
    {{- else if $.Values.settings.subpath }}

    - host: {{ $.Values.settings.env }}.{{ $.Values.settings.domain }}
      http:
          paths:
            - path: /{{ $.Values.settings.subpath }}/(.*)
              backend:
                serviceName: {{ $.Values.settings.name }}
                servicePort: 80
            - path: /{{ $.Values.settings.subpath }}(.*)
              backend:
                serviceName: {{ $.Values.settings.name }}
                servicePort: 80
    {{- else }}
    - host: {{ $.Values.settings.env }}.{{ $.Values.settings.domain }}
      http:
          paths:

            - path: /(.*)
              backend:
                serviceName: {{ $.Values.settings.name }}
                servicePort: 80
    {{- end }}
