apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.settings.name }}-configmap
  #namespace: {{ .Values.settings.env }}
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}-configmap
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{ if .Values.mysql.host }}
  mariadb-host: '{{ .Values.mysql.host }}'
  {{ else }}
  mariadb-host: '{{ .Values.settings.name }}-mysql'
  {{ end }}
  mariadb-port: {{ .Values.mysql.port | toString | quote }}
  mariadb-name: {{ .Values.mysql.name }}
  mariadb-user: {{ .Values.mysql.user }}