apiVersion: v1
entries:
  open-webconcept:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-12-16T14:34:07.3329753+01:00"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 9a03e3933e8bbab8e587ee9a8b70b290e4b49d990febe6441d9a3ec8e3106ac0
    home: "https://openwebconcept.nl/"
    icon: "https://openwebconcept.nl/wp-content/themes/openwebconcept/assets/src/images/logo-dark.png"
    name: open-webconcept
    urls:
    - open-webconcept-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-16T14:34:07.3281381+01:00"
